#!/usr/bin/env python3
"""
Backfill bean and grind onto shots that were never tagged.

    python3 backfill_recipe.py espressolog.db            # preview only
    python3 backfill_recipe.py espressolog.db --emit-sql backfill.sql

Why this exists: until migration 006 the loaded bag lived in one browser's
localStorage, so the server never learned it and a shot only got a recipe if
a human opened the Capture screen. Everything pulled and left alone is blank
— not because nothing was known, but because there was nowhere to put it.
New shots are attributed at ingest now; this is for the archive.

THE RULE, and it is deliberately timid:

  A shot is backfilled only when the nearest tagged shot BEFORE it and the
  nearest tagged shot AFTER it name the SAME bean. Two neighbours agreeing
  is strong evidence the bag never changed in between. If they disagree, a
  bag was swapped somewhere in the gap and we cannot tell which side this
  shot fell on, so it is left alone.

  At the ends of the timeline there is only one neighbour. That is used only
  within MAX_GAP_DAYS, because "the nearest tagged shot is three weeks away"
  is not evidence of anything.

Everything written is marked bean_source='backfill', so it is always
separable from what a human confirmed and trivially reversible:

    UPDATE shot SET bean_id=NULL, grind_dial=NULL, bean_source=NULL
     WHERE bean_source='backfill';
"""
import sqlite3
import sys
import datetime as dt

MAX_GAP_DAYS = 3


def parse(ts):
    return dt.datetime.fromisoformat(ts.replace("Z", "+00:00"))


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(2)
    db = sys.argv[1]
    emit = None
    if "--emit-sql" in sys.argv:
        emit = sys.argv[sys.argv.index("--emit-sql") + 1]

    conn = sqlite3.connect(db)
    conn.row_factory = sqlite3.Row
    shots = [dict(r) for r in conn.execute(
        "SELECT id, started_at, bean_id, grind_dial, yield_final_g, excluded "
        "FROM shot ORDER BY started_at")]

    tagged = [s for s in shots if s["bean_id"] is not None]
    if not tagged:
        print("nothing is tagged — no evidence to backfill from")
        return

    plans, skipped = [], []
    for s in shots:
        if s["bean_id"] is not None:
            continue
        t = parse(s["started_at"])
        before = [x for x in tagged if parse(x["started_at"]) < t]
        after = [x for x in tagged if parse(x["started_at"]) > t]
        prev = before[-1] if before else None
        nxt = after[0] if after else None

        if prev and nxt:
            if prev["bean_id"] != nxt["bean_id"]:
                skipped.append((s, "neighbours disagree — a bag changed in this gap"))
                continue
            src = prev
        else:
            src = prev or nxt
            gap = abs((parse(src["started_at"]) - t).total_seconds()) / 86400
            if gap > MAX_GAP_DAYS:
                skipped.append((s, f"only one neighbour, {gap:.1f} days away"))
                continue
        plans.append((s, src))

    print(f"{len(shots)} shots, {len(tagged)} already tagged, "
          f"{len(shots)-len(tagged)} blank\n")
    print(f"WOULD BACKFILL {len(plans)}:")
    for s, src in plans[:60]:
        print(f"  shot {s['id']:3d} {s['started_at'][:16]}  <- bean {src['bean_id']} "
              f"grind {src['grind_dial']}  (from shot {src['id']})")
    if len(plans) > 60:
        print(f"  … and {len(plans)-60} more")
    if skipped:
        print(f"\nLEFT ALONE {len(skipped)}:")
        for s, why in skipped:
            print(f"  shot {s['id']:3d} {s['started_at'][:16]}  {why}")

    if emit:
        with open(emit, "w") as f:
            f.write("-- Generated by analysis/backfill_recipe.py. Review before running.\n")
            f.write("BEGIN;\n")
            for s, src in plans:
                grind = "NULL" if src["grind_dial"] is None else repr(src["grind_dial"])
                f.write(f"UPDATE shot SET bean_id={src['bean_id']}, grind_dial={grind}, "
                        f"bean_source='backfill' WHERE id={s['id']} AND bean_id IS NULL;\n")
            f.write("COMMIT;\n")
        print(f"\nwrote {emit} ({len(plans)} statements)")


if __name__ == "__main__":
    main()
